name: dart_shp
description: An shapefile reader/writer for dart.
version: 1.0.0
homepage: https://www.hydrologis.com
repository: https://github.com/moovida/dart_shp
issue_tracker: https://github.com/moovida/dart_shp/issues

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  path: ^1.8.0
  #BSD
  dart_jts: ^0.2.0
  # BSD
  # timezone: ^0.5.7
  # BSD
  characters: ^1.1.0
  # BSD
  intl: ^0.18.0

  dart_hydrologis_utils: # ^0.6.1
    git:
      url: https://github.com/dasaki-gr/dart_hydrologis_utils.git
    # path: ../dart_hydrologis_utils/
    # git:
    #   url: https://github.com/moovida/dart_hydrologis_utils.git

dev_dependencies:
  pedantic: ^1.9.0
  test: ^1.14.2
